[all]
server01 ansible_host=192.168.254.101 ansible_user=mcbtaguiad
server01 ansible_host=192.168.254.102 ansible_user=mcbtaguiad

[debian-server]
server01 ansible_host=192.168.254.101 ansible_user=mcbtaguiad

[redhat-server]
server01 ansible_host=192.168.254.102 ansible_user=mcbtaguiad
