---
- name: Ensure groups exist
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ users | map(attribute='groups') | flatten | unique }}"

- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /bin/bash
    groups: >-
      {{ item.groups +
         ([ 'wheel' ] if item.sudo and ansible_os_family == 'RedHat'
         else [ 'sudo' ] if item.sudo else []) }}
    append: yes
  loop: "{{ users }}"

- name: Install SSH keys
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
  loop: "{{ users }}"

# - name: Allow sudo without password
#   ansible.builtin.copy:
#     dest: /etc/sudoers.d/admins
#     content: "%sudo ALL=(ALL) NOPASSWD:ALL"
#     mode: "0440"

- name: Set password aging
  ansible.builtin.command: >
    chage -m 0 -M {{ password_maxdays }} -W {{ password_warndays }} {{ item.name }}
  loop: "{{ users }}"
