---
- name: main playbook
  hosts: all
  become: true          # use sudo for all tasks
  become_method: sudo
  # ansible_become_pass: "YOUR_SUDO_PASSWORD"
  roles:
    - role: user_management
      vars:
        password_maxdays: 90
        password_warndays: 7
        users:
        - name: mark
          sudo: true
          key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDtf3e9lQR1uAypz4nrq2nDj0DvZZGONku5wO+M87wUVTistrY8REsWO2W1N/v4p2eX30Bnwk7D486jmHGpXFrpHM0EMf7wtbNj5Gt1bDHo76WSci/IEHpMrbdD5vN8wCW2ZMwJG4JC8lfFpUbdmUDWLL21Quq4q9XDx7/ugs1tCZoNybgww4eCcAi7/GAmXcS/u9huUkyiX4tbaKXQx1co7rTHd7f2u5APTVMzX0C1V9Ezc6l8I+LmjZ9rvQav5N1NgFh9B60qk9QJAb8AK9+aYy7bnBCBJ/BwIkWKYmLoVBi8j8v8UVhVdQMvQxLax41YcD8pbgU5s1O2nxM1+TqeGxrGHG6f7jqxhGWe21I7i8HPvOHNJcW4oycxFC5PNKnXNybEawE23oIDQfIG3+EudQKfAkJ3YhmrB2l+InIo0Wi9BHBIUNPzTldMS53q2teNdZR9UDqASdBdMgp4Uzfs1+LGdE5ExecSQzt4kZ8+o9oo9hmee4AYNOTWefXdip0= mtaguiad@tags-p51"
          groups:
            - admins
            - developers
        - name: christian
          sudo: false
          key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDtf3e9lQR1uAypz4nrq2nDj0DvZZGONku5wO+M87wUVTistrY8REsWO2W1N/v4p2eX30Bnwk7D486jmHGpXFrpHM0EMf7wtbNj5Gt1bDHo76WSci/IEHpMrbdD5vN8wCW2ZMwJG4JC8lfFpUbdmUDWLL21Quq4q9XDx7/ugs1tCZoNybgww4eCcAi7/GAmXcS/u9huUkyiX4tbaKXQx1co7rTHd7f2u5APTVMzX0C1V9Ezc6l8I+LmjZ9rvQav5N1NgFh9B60qk9QJAb8AK9+aYy7bnBCBJ/BwIkWKYmLoVBi8j8v8UVhVdQMvQxLax41YcD8pbgU5s1O2nxM1+TqeGxrGHG6f7jqxhGWe21I7i8HPvOHNJcW4oycxFC5PNKnXNybEawE23oIDQfIG3+EudQKfAkJ3YhmrB2l+InIo0Wi9BHBIUNPzTldMS53q2teNdZR9UDqASdBdMgp4Uzfs1+LGdE5ExecSQzt4kZ8+o9oo9hmee4AYNOTWefXdip0= mtaguiad@tags-p51"
          groups:
            - developers

    - role: access_control
      vars:
        max_logins: 2
        password_minlen: 12

     - role: package
       vars:
         unnecessary_services:
          - cups
          - rpcbind
          - nfs-server
          - vsftpd 

     - role: system_hardening
       vars:
         devel_packages_debian:
          - gcc
          - g++
          - make
          - build-essential
          - kernel-devel
          - linux-headers-$(uname -r)
        devel_packages_redhat:
          - gcc
          - gcc-c++
          - make
          - kernel-devel
          - redhat-lsb-core
          - perl
        secure_dirs:
          - /etc/ssh
          - /etc/sudoers.d
        kernel_hardening:
          net.ipv4.ip_forward: 0
          net.ipv4.conf.all.accept_redirects: 0
          net.ipv4.conf.all.send_redirects: 0
          net.ipv4.conf.all.accept_source_route: 0
          net.ipv4.tcp_syncookies: 1
          net.ipv4.conf.all.rp_filter: 1
          kernel.randomize_va_space: 2

    - role: ssh_login_alert
      vars:
        telegram_bot_token: "xxxxxxxxxxxxxxx"
        telegram_chat_id: "xxxxxxxxx"
